"""Factory column definitions derived from the supplied legacy Excel templates."""

FACTORY_COLUMNS = {
    "VER": [
        "Geändert am",
        "Titel_DE",
        "Kurzbeschreibung_DE",
        "Beschreibung Mittel_DE",
        "Beschreibung Lang_DE",
        "Titel_FR",
        "Kurzbeschreibung_FR",
        "Beschreibung Mittel_FR",
        "Beschreibung Lang_FR",
        "Titel_IT",
        "Kurzbeschreibung_IT",
        "Beschreibung Mittel_IT",
        "Beschreibung Lang_IT",
        "Titel_EN",
        "Kurzbeschreibung_EN",
        "Beschreibung Mittel_EN",
        "Beschreibung Lang_EN",
        "Zusatzinformationen_DE",
        "Zusatzinformationen_FR",
        "Zusatzinformationen_IT",
        "Zusatzinformationen_EN",
        "Details_DE",
        "Details_FR",
        "Details_IT",
        "Details_EN",
        "Weitere Informationen zur Anmeldung_DE",
        "Weitere Informationen zur Anmeldung_FR",
        "Weitere Informationen zur Anmeldung_IT",
        "Weitere Informationen zur Anmeldung_EN",
        "Ortsdetails_DE",
        "Ortsdetails_FR",
        "Ortsdetails_IT",
        "Ortsdetails_EN",
        "ÖV-Haltestelle",
        "Termine / Zeitraum",
        "Veranstaltungsort",
        "Kategorie",
        "Sprachen",
        "Zielgruppen allgemein",
        "Preis-Infos_DE",
        "Preis-Infos_FR",
        "Preis-Infos_IT",
        "Preis-Infos_EN",
        "Park/Organisation",
        "Bild 1",
        "Bild 2",
        "Dokument 1",
        "Dokument 2",
        "Weiterführende Links",
        "Kontakt",
        "Barrierefreiheit",
    ],
    "ANG": [
        "Geändert am",
        "Keywords",
        "Spezifische Zielgruppen für Webseitenfilter",
        "Titel_DE",
        "Kurzbeschreibung_DE",
        "Beschreibung Mittel_DE",
        "Beschreibung Lang_DE",
        "Titel_FR",
        "Kurzbeschreibung_FR",
        "Beschreibung Mittel_FR",
        "Beschreibung Lang_FR",
        "Titel_IT",
        "Kurzbeschreibung_IT",
        "Beschreibung Mittel_IT",
        "Beschreibung Lang_IT",
        "Titel_EN",
        "Kurzbeschreibung_EN",
        "Beschreibung Mittel_EN",
        "Beschreibung Lang_EN",
        "Zusatzinformationen_DE",
        "Zusatzinformationen_FR",
        "Zusatzinformationen_IT",
        "Zusatzinformationen_EN",
        "Anmeldung erforderlich",
        "Anmeldung bei",
        "Anmeldungslink",
        "Anforderungen_DE",
        "Anforderungen_FR",
        "Sicherheitshinweise_DE",
        "Sicherheitshinweise_FR",
        "Sicherheitshinweise_IT",
        "Sicherheitshinweise_EN",
        "ÖV-Haltestelle",
        "Startort - ÖV-Haltestelle",
        "Zielort - ÖV-Haltestelle",
        "Zeitbedarf",
        "Schwierigkeitsgrad Technik",
        "Termine / Zeitraum",
        "Durchführungsdaten/-zeitraum",
        "Hauptkategorie",
        "Kategorie",
        "Sprachen",
        "Kontakt",
        "Veranstaltungsort",
        "Zielgruppen allgemein",
        "Preis-Infos_DE",
        "Preis-Infos_FR",
        "Preis-Infos_IT",
        "Preis-Infos_EN",
        "Öffnungszeiten_DE",
        "Öffnungszeiten_FR",
        "Öffnungszeiten_IT",
        "Öffnungszeiten_EN",
        "Bild 1",
        "Bild 2",
        "Dokument 1",
        "Dokument 2",
        "Weiterführende Links",
        "barrierefreiheit",
    ],
}

# Export field names changed after the old templates were created.
# These aliases let the factory preset follow the same semantic field when possible.
ALIASES = {
    "Kurzbeschreibung_DE": ["Untertitel_DE"],
    "Kurzbeschreibung_FR": ["Untertitel_FR"],
    "Kurzbeschreibung_IT": ["Untertitel_IT"],
    "Kurzbeschreibung_EN": ["Untertitel_EN"],
}

# In ANG, the factory ÖV field belongs to the later route/tour block rather than
# the earlier general-location field. Selecting the last duplicate preserves that intent.
PREFER_LAST_DUPLICATE = {
    "VER": {"ÖV-Haltestelle"},
    "ANG": {"ÖV-Haltestelle"},
}
